### ISSUE TITLE
Room - Shelf - Book - Paper 컨셉 정리

### ISSUE THREAD

**Issue by wooklym** [fincil/boom#5]

**Comment by indiev** [comment]
Paper - 기본적인 단위로서 데이터를 기록하거나 읽는다. 사용자가 원하는 크기 또는 화면 하나에 보일 수 있는 크기 또는 데이터가 표현되어지는 한 호흡을 1장으로 한다. 1장의 형식에 따라 타입을 갖는다. 타입 예) plain, grid, animation, complex, multi 등. Paper에 대한 형상관리가 된다.

Book - 같은 목적과 흐름을 갖는 Paper가 하나 이상이 모여 Book이 된다. Paper에 대한 Index갖는다. Chapter(시작 페이퍼와 끝 페이퍼 포인터)를 가질 수 있다. 같은 내용은 오래된 데이터를 분류하거나 내용의 큰 변화에 따라 여러 권으로 나눌 수 있다. Book부터 통계 정보를 제공한다. Book별로 의견이나 아이디어등의 생각을 나눌 수 있는 폼을 제공한다. 형상관리되는 Paper에 대한 버전관리를 제공한다.

Shelf - Book을 여러권을 이상을 관심에 따라 묶어 관리한다.  우선순위에 따라 Book 또는 Shelf들이 나열 된다. 자기 Book 외에 다른 사람의 Book도 넣어둘 수 있다. ex) 요리 Shelf, 업무 Shelf, 일기 Shelf 등

Room - 목적에 따라 Room을 갖는다. 자신만 사용할 수 있는 Room도 있으며, 내가 아는 사람과 공동으로 쓰는 공간과 모르는 다수의 사람들과 함께 이용하는 Room도 존재한다. ex) 개인이 쓰는 개인방, 팀원과 함께 쓰는 팀방, 회사동료와 함께 쓰는 사무실, 여러 사람들이 함께쓰는 도서관 등

**Comment by wooklym** [comment]
위키로 이동시키겠습니다.
